"""db change for signup login new chnange

Revision ID: 09476973d880
Revises: 057bfa329712
Create Date: 2026-05-19 16:06:49.317397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09476973d880'
down_revision: Union[str, Sequence[str], None] = '057bfa329712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_role_email', 'users', ['role', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_role_email', 'users', type_='unique')
    # ### end Alembic commands ###
