"""devices locate added in the platform settings

Revision ID: 12dc341f3965
Revises: 95f76edf4bec
Create Date: 2026-05-22 11:12:27.195297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dc341f3965'
down_revision: Union[str, Sequence[str], None] = '95f76edf4bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('driver_max_active_sessions', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.add_column('user_sessions', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('user_sessions', sa.Column('device_family', sa.String(length=120), nullable=True))
    op.add_column('user_sessions', sa.Column('platform', sa.String(length=120), nullable=True))
    op.add_column('user_sessions', sa.Column('browser', sa.String(length=120), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'browser')
    op.drop_column('user_sessions', 'platform')
    op.drop_column('user_sessions', 'device_family')
    op.drop_column('user_sessions', 'device_name')
    op.drop_column('platform_settings', 'driver_max_active_sessions')
    # ### end Alembic commands ###
