"""add seat number to trip bookings

Revision ID: 152d8fb288d5
Revises: 70997f499431
Create Date: 2026-05-18 10:54:58.315795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152d8fb288d5'
down_revision: Union[str, Sequence[str], None] = '70997f499431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "trip_bookings",
        sa.Column("seat_number", sa.Integer(), nullable=True),
    )

    op.execute(
        "UPDATE trip_bookings SET seat_number = 1 WHERE seat_number IS NULL"
    )

    op.alter_column(
        "trip_bookings",
        "seat_number",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.create_check_constraint(
        "ck_trip_bookings_seat_number_positive",
        "trip_bookings",
        "seat_number > 0",
    )

    op.create_index(
        "ix_trip_bookings_trip_seat_status",
        "trip_bookings",
        ["scheduled_trip_id", "seat_number", "booking_status"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_bookings_trip_seat_status', table_name='trip_bookings')
    op.drop_column('trip_bookings', 'seat_number')
    # ### end Alembic commands ###
