"""Rf_id added in the exiting tables

Revision ID: 190644f9b03a
Revises: 328f6acf8c76
Create Date: 2026-05-11 11:39:52.530034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190644f9b03a'
down_revision: Union[str, Sequence[str], None] = '328f6acf8c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_trips', sa.Column('rfid_reserved_seat_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('vehicles', sa.Column('default_rfid_reserved_seat_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'default_rfid_reserved_seat_count')
    op.drop_column('scheduled_trips', 'rfid_reserved_seat_count')
    # ### end Alembic commands ###
