"""col and enum in payout details driver profile

Revision ID: 210a5686ec0b
Revises: b16834119213
Create Date: 2026-04-20 09:32:27.237197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210a5686ec0b'
down_revision: Union[str, Sequence[str], None] = 'b16834119213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_payout_details', sa.Column('razorpay_stakeholder_id', sa.String(length=64), nullable=True))
    op.add_column('driver_payout_details', sa.Column('razorpay_route_product_id', sa.String(length=64), nullable=True))
    op.add_column('driver_payout_details', sa.Column('route_product_status', sa.Enum('not_requested', 'requested', 'under_review', 'needs_clarification', 'activated', 'suspended', name='route_product_status', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('driver_payout_details', sa.Column('route_product_requirements_json', sa.Text(), nullable=True))
    op.add_column('driver_payout_details', sa.Column('provider_onboarding_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'driver_payout_details', ['razorpay_stakeholder_id'])
    op.create_unique_constraint(None, 'driver_payout_details', ['razorpay_route_product_id'])
    op.add_column('driver_profiles', sa.Column('residential_street_line_1', sa.String(length=255), nullable=True))
    op.add_column('driver_profiles', sa.Column('residential_street_line_2', sa.String(length=255), nullable=True))
    op.add_column('driver_profiles', sa.Column('residential_city', sa.String(length=120), nullable=True))
    op.add_column('driver_profiles', sa.Column('residential_state', sa.String(length=120), nullable=True))
    op.add_column('driver_profiles', sa.Column('residential_postal_code', sa.String(length=20), nullable=True))
    op.add_column('driver_profiles', sa.Column('residential_country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'residential_country')
    op.drop_column('driver_profiles', 'residential_postal_code')
    op.drop_column('driver_profiles', 'residential_state')
    op.drop_column('driver_profiles', 'residential_city')
    op.drop_column('driver_profiles', 'residential_street_line_2')
    op.drop_column('driver_profiles', 'residential_street_line_1')
    op.drop_constraint(None, 'driver_payout_details', type_='unique')
    op.drop_constraint(None, 'driver_payout_details', type_='unique')
    op.alter_column('driver_payout_details', 'linked_account_status',
               existing_type=sa.Enum('not_created', 'created', 'under_review', 'needs_clarification', 'active', 'blocked', 'rejected', 'deleted', name='linked_account_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('driver_payout_details', 'provider_onboarding_last_synced_at')
    op.drop_column('driver_payout_details', 'route_product_requirements_json')
    op.drop_column('driver_payout_details', 'route_product_status')
    op.drop_column('driver_payout_details', 'razorpay_route_product_id')
    op.drop_column('driver_payout_details', 'razorpay_stakeholder_id')
    # ### end Alembic commands ###
