"""create 4 col at vehicle

Revision ID: 28790fa0164a
Revises: 5e6d8ede79f4
Create Date: 2026-04-17 11:40:46.426337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28790fa0164a'
down_revision: Union[str, Sequence[str], None] = '5e6d8ede79f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('rc_number', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('engine_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_no', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('rc_owner_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'rc_owner_name')
    op.drop_column('vehicles', 'chassis_no')
    op.drop_column('vehicles', 'engine_number')
    op.drop_column('vehicles', 'rc_number')
    # ### end Alembic commands ###
