"""Rf_id inventery

Revision ID: 328f6acf8c76
Revises: 4d8732e43c86
Create Date: 2026-05-11 11:25:47.462899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328f6acf8c76'
down_revision: Union[str, Sequence[str], None] = '4d8732e43c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_cards',
    sa.Column('card_uid_hash', sa.String(length=255), nullable=False),
    sa.Column('card_uid_masked', sa.String(length=64), nullable=True),
    sa.Column('inventory_status', sa.Enum('inventory', 'assigned', 'lost', 'decommissioned', name='rfid_card_inventory_status', native_enum=False, create_constraint=True), server_default=sa.text("'inventory'"), nullable=False),
    sa.Column('authorization_status', sa.Enum('allowed', 'blocked', name='rfid_card_authorization_status', native_enum=False, create_constraint=True), server_default=sa.text("'allowed'"), nullable=False),
    sa.Column('assigned_passenger_user_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("card_uid_hash <> ''", name='ck_rfid_cards_uid_hash_nonempty'),
    sa.ForeignKeyConstraint(['assigned_passenger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_uid_hash')
    )
    op.create_index('ix_rfid_cards_assigned_passenger', 'rfid_cards', ['assigned_passenger_user_id'], unique=False)
    op.create_index('ix_rfid_cards_authorization_status', 'rfid_cards', ['authorization_status'], unique=False)
    op.create_index('ix_rfid_cards_inventory_status', 'rfid_cards', ['inventory_status'], unique=False)
    op.create_table('rfid_card_assignments',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['rfid_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unassigned_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_card_assignments_card_assigned', 'rfid_card_assignments', ['card_id', 'assigned_at'], unique=False)
    op.create_index('ix_rfid_card_assignments_passenger_assigned', 'rfid_card_assignments', ['passenger_user_id', 'assigned_at'], unique=False)
    op.create_table('rfid_devices',
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_seen_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("serial_number <> ''", name='ck_rfid_devices_serial_number_nonempty'),
    sa.CheckConstraint('last_seen_lat IS NULL OR (last_seen_lat >= -90 AND last_seen_lat <= 90)', name='ck_rfid_devices_last_seen_lat_range'),
    sa.CheckConstraint('last_seen_lng IS NULL OR (last_seen_lng >= -180 AND last_seen_lng <= 180)', name='ck_rfid_devices_last_seen_lng_range'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_rfid_devices_is_active', 'rfid_devices', ['is_active'], unique=False)
    op.create_index('ix_rfid_devices_last_seen_at', 'rfid_devices', ['last_seen_at'], unique=False)
    op.create_index('ix_rfid_devices_vehicle_id', 'rfid_devices', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'rfid_card_accounts', 'rfid_cards', ['card_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfid_card_accounts', type_='foreignkey')
    op.drop_index('ix_rfid_devices_vehicle_id', table_name='rfid_devices')
    op.drop_index('ix_rfid_devices_last_seen_at', table_name='rfid_devices')
    op.drop_index('ix_rfid_devices_is_active', table_name='rfid_devices')
    op.drop_table('rfid_devices')
    op.drop_index('ix_rfid_card_assignments_passenger_assigned', table_name='rfid_card_assignments')
    op.drop_index('ix_rfid_card_assignments_card_assigned', table_name='rfid_card_assignments')
    op.drop_table('rfid_card_assignments')
    op.drop_index('ix_rfid_cards_inventory_status', table_name='rfid_cards')
    op.drop_index('ix_rfid_cards_authorization_status', table_name='rfid_cards')
    op.drop_index('ix_rfid_cards_assigned_passenger', table_name='rfid_cards')
    op.drop_table('rfid_cards')
    # ### end Alembic commands ###
