"""create a table

Revision ID: 38cdeafd0ebb
Revises: afd209c85377
Create Date: 2026-04-16 11:35:24.837347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cdeafd0ebb'
down_revision: Union[str, Sequence[str], None] = 'afd209c85377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_leases',
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("job_name <> ''", name='ck_job_leases_job_name_nonempty'),
    sa.CheckConstraint("owner_id <> ''", name='ck_job_leases_owner_id_nonempty'),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_index('ix_job_leases_lease_expires_at', 'job_leases', ['lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_leases_lease_expires_at', table_name='job_leases')
    op.drop_table('job_leases')
    # ### end Alembic commands ###
