"""Rf_id tables added

Revision ID: 3912fc1fde39
Revises: 88070788f5a2
Create Date: 2026-05-12 10:06:29.808770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3912fc1fde39'
down_revision: Union[str, Sequence[str], None] = '88070788f5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_recharge_funding_allocations',
    sa.Column('funding_lot_id', sa.String(length=36), nullable=False),
    sa.Column('recharge_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=True),
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('source_razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reversed_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rfid_funding_allocations_amount_positive'),
    sa.CheckConstraint('reversed_amount <= amount', name='ck_rfid_funding_allocations_reversed_not_above_amount'),
    sa.CheckConstraint('reversed_amount >= 0', name='ck_rfid_funding_allocations_reversed_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['rfid_card_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['funding_lot_id'], ['rfid_funding_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recharge_id'], ['rfid_recharges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfid_ride_id'], ['rfid_trip_rides.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funding_lot_id', 'rfid_ride_id', name='uq_rfid_funding_allocations_lot_ride')
    )
    op.create_index('ix_rfid_funding_allocations_driver_trip', 'rfid_recharge_funding_allocations', ['driver_user_id', 'scheduled_trip_id'], unique=False)
    op.create_index('ix_rfid_funding_allocations_lot', 'rfid_recharge_funding_allocations', ['funding_lot_id'], unique=False)
    op.create_index('ix_rfid_funding_allocations_razorpay_payment', 'rfid_recharge_funding_allocations', ['source_razorpay_payment_id'], unique=False)
    op.create_index('ix_rfid_funding_allocations_recharge', 'rfid_recharge_funding_allocations', ['recharge_id'], unique=False)
    op.create_index('ix_rfid_funding_allocations_ride', 'rfid_recharge_funding_allocations', ['rfid_ride_id'], unique=False)
    op.drop_constraint(op.f('rfid_payout_transfers_source_funding_allocation_id_fkey'), 'rfid_payout_transfers', type_='foreignkey')
    op.create_foreign_key(None, 'rfid_payout_transfers', 'rfid_recharge_funding_allocations', ['source_funding_allocation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfid_payout_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('rfid_payout_transfers_source_funding_allocation_id_fkey'), 'rfid_payout_transfers', 'rfid_ride_funding_allocations', ['source_funding_allocation_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_rfid_funding_allocations_ride', table_name='rfid_recharge_funding_allocations')
    op.drop_index('ix_rfid_funding_allocations_recharge', table_name='rfid_recharge_funding_allocations')
    op.drop_index('ix_rfid_funding_allocations_razorpay_payment', table_name='rfid_recharge_funding_allocations')
    op.drop_index('ix_rfid_funding_allocations_lot', table_name='rfid_recharge_funding_allocations')
    op.drop_index('ix_rfid_funding_allocations_driver_trip', table_name='rfid_recharge_funding_allocations')
    op.drop_table('rfid_recharge_funding_allocations')
    # ### end Alembic commands ###
