"""add in db

Revision ID: 3e5d5f84deb3
Revises: b4a02bd34517
Create Date: 2026-04-06 11:31:10.551440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5d5f84deb3'
down_revision: Union[str, Sequence[str], None] = 'b4a02bd34517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_bookings', sa.Column('refund_retry_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trip_bookings', sa.Column('refund_attempt_count', sa.Integer(), nullable=True))
    op.create_index('ix_trip_bookings_status_refund_retry_after', 'trip_bookings', ['booking_status', 'refund_retry_after'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_bookings_status_refund_retry_after', table_name='trip_bookings')
    op.drop_column('trip_bookings', 'refund_attempt_count')
    op.drop_column('trip_bookings', 'refund_retry_after')
    op.alter_column('scheduled_trips', 'status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', 'premature_end', name='scheduled_trip_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
