"""Rf id tables are added

Revision ID: 4d8732e43c86
Revises: 210a5686ec0b
Create Date: 2026-05-11 11:13:30.293618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8732e43c86'
down_revision: Union[str, Sequence[str], None] = '210a5686ec0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_card_accounts',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('held_balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency <> ''", name='ck_rfid_card_accounts_currency_nonempty'),
    sa.CheckConstraint('current_balance >= 0', name='ck_rfid_card_accounts_current_balance_nonnegative'),
    sa.CheckConstraint('held_balance <= current_balance', name='ck_rfid_card_accounts_hold_not_above_balance'),
    sa.CheckConstraint('held_balance >= 0', name='ck_rfid_card_accounts_held_balance_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_table('rfid_recharges',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'cancelled', 'manually_recorded', 'credited', 'reversed', name='rfid_recharge_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_type', sa.Enum('admin_manual', 'razorpay_user_recharge', name='rfid_recharge_source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('razorpay_status', sa.String(length=64), nullable=True),
    sa.Column('razorpay_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('provider_payload_json', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('verified_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('credited_ledger_entry_id', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rfid_recharges_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['rfid_card_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_recharges_account_created', 'rfid_recharges', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_recharges_card_created', 'rfid_recharges', ['card_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_recharges_razorpay_order', 'rfid_recharges', ['razorpay_order_id'], unique=False)
    op.create_index('ix_rfid_recharges_razorpay_payment', 'rfid_recharges', ['razorpay_payment_id'], unique=False)
    op.create_table('rfid_funding_lots',
    sa.Column('recharge_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.Enum('razorpay_payment', 'admin_manual_pool', name='rfid_funding_lot_source_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('available', 'exhausted', 'reversed', name='rfid_funding_lot_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('remaining_amount <= source_amount', name='ck_rfid_funding_lots_remaining_not_above_source'),
    sa.CheckConstraint('remaining_amount >= 0', name='ck_rfid_funding_lots_remaining_nonnegative'),
    sa.CheckConstraint('source_amount > 0', name='ck_rfid_funding_lots_source_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['rfid_card_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recharge_id'], ['rfid_recharges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_funding_lots_account_status', 'rfid_funding_lots', ['account_id', 'status'], unique=False)
    op.create_index('ix_rfid_funding_lots_card_status', 'rfid_funding_lots', ['card_id', 'status'], unique=False)
    op.create_index('ix_rfid_funding_lots_recharge', 'rfid_funding_lots', ['recharge_id'], unique=False)
    op.create_table('rfid_ledger_entries',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=True),
    sa.Column('entry_type', sa.Enum('recharge_credit', 'fare_hold', 'fare_debit', 'hold_release', 'admin_adjustment_credit', 'admin_adjustment_debit', 'card_return_sweep', 'card_decommission_sweep', 'refund', 'reversal', 'fare_reversal_credit', 'hold_reversal', 'funding_reversal', name='rfid_ledger_entry_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('held_delta', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('held_balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_recharge_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=True),
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=True),
    sa.Column('stop_id', sa.String(length=36), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('reverses_ledger_entry_id', sa.String(length=36), nullable=True),
    sa.Column('reversed_by_ledger_entry_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('balance_after >= 0', name='ck_rfid_ledger_entries_balance_after_nonnegative'),
    sa.CheckConstraint('held_balance_after <= balance_after', name='ck_rfid_ledger_entries_hold_after_not_above_balance'),
    sa.CheckConstraint('held_balance_after >= 0', name='ck_rfid_ledger_entries_held_after_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['rfid_card_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_ledger_entry_id'], ['rfid_ledger_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reverses_ledger_entry_id'], ['rfid_ledger_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_recharge_id'], ['rfid_recharges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_ledger_entries_account_created', 'rfid_ledger_entries', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_ledger_entries_card_created', 'rfid_ledger_entries', ['card_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_ledger_entries_razorpay_payment', 'rfid_ledger_entries', ['razorpay_payment_id'], unique=False)
    op.create_index('ix_rfid_ledger_entries_recharge', 'rfid_ledger_entries', ['source_recharge_id'], unique=False)
    op.create_index('ix_rfid_ledger_entries_ride', 'rfid_ledger_entries', ['rfid_ride_id'], unique=False)
    op.create_index('ix_rfid_ledger_entries_trip', 'rfid_ledger_entries', ['scheduled_trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rfid_ledger_entries_trip', table_name='rfid_ledger_entries')
    op.drop_index('ix_rfid_ledger_entries_ride', table_name='rfid_ledger_entries')
    op.drop_index('ix_rfid_ledger_entries_recharge', table_name='rfid_ledger_entries')
    op.drop_index('ix_rfid_ledger_entries_razorpay_payment', table_name='rfid_ledger_entries')
    op.drop_index('ix_rfid_ledger_entries_card_created', table_name='rfid_ledger_entries')
    op.drop_index('ix_rfid_ledger_entries_account_created', table_name='rfid_ledger_entries')
    op.drop_table('rfid_ledger_entries')
    op.drop_index('ix_rfid_funding_lots_recharge', table_name='rfid_funding_lots')
    op.drop_index('ix_rfid_funding_lots_card_status', table_name='rfid_funding_lots')
    op.drop_index('ix_rfid_funding_lots_account_status', table_name='rfid_funding_lots')
    op.drop_table('rfid_funding_lots')
    op.drop_index('ix_rfid_recharges_razorpay_payment', table_name='rfid_recharges')
    op.drop_index('ix_rfid_recharges_razorpay_order', table_name='rfid_recharges')
    op.drop_index('ix_rfid_recharges_card_created', table_name='rfid_recharges')
    op.drop_index('ix_rfid_recharges_account_created', table_name='rfid_recharges')
    op.drop_table('rfid_recharges')
    op.drop_table('rfid_card_accounts')
    # ### end Alembic commands ###
