"""adhaar and pan nullable true

Revision ID: 59a29f0e1725
Revises: 6d1d5badfa77
Create Date: 2026-04-01 10:50:29.028045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a29f0e1725'
down_revision: Union[str, Sequence[str], None] = '6d1d5badfa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'aadhaar_file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('driver_profiles', 'pan_file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_profiles', 'pan_file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('driver_profiles', 'aadhaar_file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
