"""create a col at vehicle

Revision ID: 5e6d8ede79f4
Revises: 38cdeafd0ebb
Create Date: 2026-04-16 17:27:39.926027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6d8ede79f4'
down_revision: Union[str, Sequence[str], None] = '38cdeafd0ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('ownership_type', sa.Enum('self', 'rented', name='vehicle_ownership_type', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('vehicles', sa.Column('authentication_file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'authentication_file_path')
    op.drop_column('vehicles', 'ownership_type')
    # ### end Alembic commands ###
