"""add a table support

Revision ID: 656ccc31775b
Revises: a2e4d4658952
Create Date: 2026-04-03 12:37:22.829303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656ccc31775b'
down_revision: Union[str, Sequence[str], None] = 'a2e4d4658952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolved', 'rejected', name='support_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolved_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("description <> ''", name='ck_support_description_nonempty'),
    sa.CheckConstraint("subject <> ''", name='ck_support_subject_nonempty'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_user_status', 'support_tickets', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_user_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###
