"""add in db for socket

Revision ID: 6925d0521c43
Revises: 3e5d5f84deb3
Create Date: 2026-04-07 12:39:55.394832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6925d0521c43'
down_revision: Union[str, Sequence[str], None] = '3e5d5f84deb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("message <> ''", name='ck_user_notifications_message_nonempty'),
    sa.CheckConstraint("title <> ''", name='ck_user_notifications_title_nonempty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notifications_user_created', 'user_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_user_notifications_user_read', 'user_notifications', ['user_id', 'read_at'], unique=False)
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index('ix_user_notifications_user_read', table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_created', table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
