"""db change for signup login new chnange and otp change in db

Revision ID: 6fb141b21526
Revises: 09476973d880
Create Date: 2026-05-19 16:13:27.747061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb141b21526'
down_revision: Union[str, Sequence[str], None] = '09476973d880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('role', sa.Enum('admin', 'driver', 'passenger', name='otp_user_role', native_enum=False, create_constraint=True), nullable=False))
    op.drop_index(op.f('ix_otp_requests_email_expires_at'), table_name='otp_requests')
    op.create_index('ix_otp_requests_email_role_purpose_expires_at', 'otp_requests', ['email', 'role', 'purpose', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_otp_requests_email_role_purpose_expires_at', table_name='otp_requests')
    op.create_index(op.f('ix_otp_requests_email_expires_at'), 'otp_requests', ['email', 'expires_at'], unique=False)
    op.drop_column('otp_requests', 'role')
    # ### end Alembic commands ###
