"""add a table

Revision ID: 71d78c0ca63a
Revises: 89336f803407
Create Date: 2026-04-02 16:31:55.285028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d78c0ca63a'
down_revision: Union[str, Sequence[str], None] = '89336f803407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_events',
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('stop_id', sa.String(length=36), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_trip_id', 'stop_id', name='uq_trip_events_trip_stop')
    )
    op.create_index('ix_trip_events_trip_stop', 'trip_events', ['scheduled_trip_id', 'stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_events_trip_stop', table_name='trip_events')
    op.drop_table('trip_events')
    # ### end Alembic commands ###
