"""add relation

Revision ID: 7f5ebabcb49c
Revises: 12dc341f3965
Create Date: 2026-06-01 10:31:54.844415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5ebabcb49c'
down_revision: Union[str, Sequence[str], None] = '12dc341f3965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passenger_traveller_profiles',
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('relationship_label', sa.String(length=80), nullable=True),
    sa.Column('is_self', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("full_name <> ''", name='ck_passenger_traveller_profiles_full_name_nonempty'),
    sa.CheckConstraint("phone <> ''", name='ck_passenger_traveller_profiles_phone_nonempty'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passenger_traveller_profiles_owner_active', 'passenger_traveller_profiles', ['owner_user_id', 'is_active'], unique=False)
    op.create_index('ix_passenger_traveller_profiles_owner_self', 'passenger_traveller_profiles', ['owner_user_id', 'is_self'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passenger_traveller_profiles_owner_self', table_name='passenger_traveller_profiles')
    op.drop_index('ix_passenger_traveller_profiles_owner_active', table_name='passenger_traveller_profiles')
    op.drop_table('passenger_traveller_profiles')
    # ### end Alembic commands ###
