"""Rf_id tables added

Revision ID: 88070788f5a2
Revises: 09d77aa834b5
Create Date: 2026-05-11 12:36:24.383822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88070788f5a2'
down_revision: Union[str, Sequence[str], None] = '09d77aa834b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_trip_rides',
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_stop_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_sequence_no', sa.Integer(), nullable=False),
    sa.Column('board_rfid_scan_event_id', sa.String(length=36), nullable=True),
    sa.Column('boarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('board_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('board_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('dropoff_stop_id', sa.String(length=36), nullable=True),
    sa.Column('dropoff_sequence_no', sa.Integer(), nullable=True),
    sa.Column('drop_rfid_scan_event_id', sa.String(length=36), nullable=True),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drop_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('drop_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.Enum('boarded', 'completed', 'cancelled', 'settlement_failed', name='rfid_ride_status', native_enum=False, create_constraint=True), server_default=sa.text("'boarded'"), nullable=False),
    sa.Column('hold_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('fare_reversed_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('commission_percent_snapshot', sa.Numeric(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('driver_payout_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('driver_payout_reversed_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('platform_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('platform_amount_reversed', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('transfer_status', sa.Enum('not_ready', 'ready', 'transferred', 'withheld', 'reversed', 'failed', name='transfer_status', native_enum=False, create_constraint=True), server_default=sa.text("'not_ready'"), nullable=False),
    sa.Column('transfer_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('board_lat >= -90 AND board_lat <= 90', name='ck_rfid_trip_rides_board_lat_range'),
    sa.CheckConstraint('board_lng >= -180 AND board_lng <= 180', name='ck_rfid_trip_rides_board_lng_range'),
    sa.CheckConstraint('commission_amount >= 0', name='ck_rfid_trip_rides_commission_amount_nonnegative'),
    sa.CheckConstraint('commission_percent_snapshot >= 0', name='ck_rfid_trip_rides_commission_percent_nonnegative'),
    sa.CheckConstraint('driver_payout_amount >= 0', name='ck_rfid_trip_rides_driver_payout_nonnegative'),
    sa.CheckConstraint('driver_payout_reversed_amount >= 0 AND driver_payout_reversed_amount <= driver_payout_amount', name='ck_rfid_trip_rides_driver_payout_reversal_valid'),
    sa.CheckConstraint('drop_lat IS NULL OR (drop_lat >= -90 AND drop_lat <= 90)', name='ck_rfid_trip_rides_drop_lat_range'),
    sa.CheckConstraint('drop_lng IS NULL OR (drop_lng >= -180 AND drop_lng <= 180)', name='ck_rfid_trip_rides_drop_lng_range'),
    sa.CheckConstraint('dropoff_sequence_no IS NULL OR dropoff_sequence_no > pickup_sequence_no', name='ck_rfid_trip_rides_drop_after_pickup'),
    sa.CheckConstraint('fare_amount >= 0', name='ck_rfid_trip_rides_fare_amount_nonnegative'),
    sa.CheckConstraint('fare_reversed_amount >= 0 AND fare_reversed_amount <= fare_amount', name='ck_rfid_trip_rides_fare_reversal_valid'),
    sa.CheckConstraint('hold_amount >= 0', name='ck_rfid_trip_rides_hold_amount_nonnegative'),
    sa.CheckConstraint('pickup_sequence_no >= 0', name='ck_rfid_trip_rides_pickup_sequence_nonnegative'),
    sa.CheckConstraint('platform_amount >= 0', name='ck_rfid_trip_rides_platform_amount_nonnegative'),
    sa.CheckConstraint('platform_amount_reversed >= 0 AND platform_amount_reversed <= platform_amount', name='ck_rfid_trip_rides_platform_reversal_valid'),
    sa.ForeignKeyConstraint(['account_id'], ['rfid_card_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['card_id'], ['rfid_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dropoff_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_trip_rides_account_status', 'rfid_trip_rides', ['account_id', 'status'], unique=False)
    op.create_index('ix_rfid_trip_rides_boarded_at', 'rfid_trip_rides', ['boarded_at'], unique=False)
    op.create_index('ix_rfid_trip_rides_card_status', 'rfid_trip_rides', ['card_id', 'status'], unique=False)
    op.create_index('ix_rfid_trip_rides_driver_status', 'rfid_trip_rides', ['driver_user_id', 'status'], unique=False)
    op.create_index('ix_rfid_trip_rides_dropped_at', 'rfid_trip_rides', ['dropped_at'], unique=False)
    op.create_index('ix_rfid_trip_rides_transfer_status', 'rfid_trip_rides', ['transfer_status'], unique=False)
    op.create_index('ix_rfid_trip_rides_trip_status', 'rfid_trip_rides', ['scheduled_trip_id', 'status'], unique=False)
    op.create_index('ix_rfid_trip_rides_vehicle_status', 'rfid_trip_rides', ['vehicle_id', 'status'], unique=False)
    op.create_table('rfid_scan_events',
    sa.Column('scan_type', sa.Enum('board', 'drop', name='rfid_scan_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('device_serial_snapshot', sa.String(length=120), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=True),
    sa.Column('card_uid_hash_snapshot', sa.String(length=255), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=True),
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=True),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('driver_user_id', sa.String(length=36), nullable=True),
    sa.Column('matched_stop_id', sa.String(length=36), nullable=True),
    sa.Column('matched_route_stop_id', sa.String(length=36), nullable=True),
    sa.Column('matched_sequence_no', sa.Integer(), nullable=True),
    sa.Column('active_trip_event_id', sa.String(length=36), nullable=True),
    sa.Column('active_stop_arrival_time_snapshot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_stop_departure_time_snapshot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('scan_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('within_radius', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('distance_from_stop_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=120), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("card_uid_hash_snapshot <> ''", name='ck_rfid_scan_events_card_uid_hash_snapshot_nonempty'),
    sa.CheckConstraint("device_serial_snapshot <> ''", name='ck_rfid_scan_events_device_serial_snapshot_nonempty'),
    sa.CheckConstraint('distance_from_stop_meters IS NULL OR distance_from_stop_meters >= 0', name='ck_rfid_scan_events_distance_nonnegative'),
    sa.CheckConstraint('matched_sequence_no IS NULL OR matched_sequence_no >= 0', name='ck_rfid_scan_events_matched_sequence_nonnegative'),
    sa.CheckConstraint('scan_lat IS NULL OR (scan_lat >= -90 AND scan_lat <= 90)', name='ck_rfid_scan_events_scan_lat_range'),
    sa.CheckConstraint('scan_lng IS NULL OR (scan_lng >= -180 AND scan_lng <= 180)', name='ck_rfid_scan_events_scan_lng_range'),
    sa.ForeignKeyConstraint(['active_trip_event_id'], ['trip_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['card_id'], ['rfid_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['rfid_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_route_stop_id'], ['route_stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfid_ride_id'], ['rfid_trip_rides.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_scan_events_accepted_created', 'rfid_scan_events', ['accepted', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_card_created', 'rfid_scan_events', ['card_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_device_created', 'rfid_scan_events', ['device_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_ride_created', 'rfid_scan_events', ['rfid_ride_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_scan_type_created', 'rfid_scan_events', ['scan_type', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_trip_created', 'rfid_scan_events', ['scheduled_trip_id', 'created_at'], unique=False)
    op.create_index('ix_rfid_scan_events_vehicle_created', 'rfid_scan_events', ['vehicle_id', 'created_at'], unique=False)
    op.create_table('rfid_ride_funding_allocations',
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=False),
    sa.Column('funding_lot_id', sa.String(length=36), nullable=False),
    sa.Column('recharge_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rfid_ride_funding_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['funding_lot_id'], ['rfid_funding_lots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recharge_id'], ['rfid_recharges.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfid_ride_id'], ['rfid_trip_rides.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_ride_funding_allocations_funding_lot', 'rfid_ride_funding_allocations', ['funding_lot_id'], unique=False)
    op.create_index('ix_rfid_ride_funding_allocations_razorpay_payment', 'rfid_ride_funding_allocations', ['razorpay_payment_id'], unique=False)
    op.create_index('ix_rfid_ride_funding_allocations_recharge', 'rfid_ride_funding_allocations', ['recharge_id'], unique=False)
    op.create_index('ix_rfid_ride_funding_allocations_ride', 'rfid_ride_funding_allocations', ['rfid_ride_id'], unique=False)
    op.create_table('rfid_payout_transfers',
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('source_recharge_id', sa.String(length=36), nullable=True),
    sa.Column('source_funding_allocation_id', sa.String(length=36), nullable=True),
    sa.Column('source_razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('linked_account_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ready', 'created', 'processed', 'failed', 'withheld', 'reversed', name='rfid_payout_transfer_status', native_enum=False, create_constraint=True), server_default=sa.text("'ready'"), nullable=False),
    sa.Column('razorpay_transfer_id', sa.String(length=120), nullable=True),
    sa.Column('provider_response_json', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rfid_payout_transfers_amount_positive'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfid_ride_id'], ['rfid_trip_rides.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_funding_allocation_id'], ['rfid_ride_funding_allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_recharge_id'], ['rfid_recharges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_payout_transfers_driver_status', 'rfid_payout_transfers', ['driver_user_id', 'status'], unique=False)
    op.create_index('ix_rfid_payout_transfers_razorpay_transfer', 'rfid_payout_transfers', ['razorpay_transfer_id'], unique=False)
    op.create_index('ix_rfid_payout_transfers_ride', 'rfid_payout_transfers', ['rfid_ride_id'], unique=False)
    op.create_index('ix_rfid_payout_transfers_source_funding_allocation', 'rfid_payout_transfers', ['source_funding_allocation_id'], unique=False)
    op.create_index('ix_rfid_payout_transfers_source_razorpay_payment', 'rfid_payout_transfers', ['source_razorpay_payment_id'], unique=False)
    op.create_index('ix_rfid_payout_transfers_source_recharge', 'rfid_payout_transfers', ['source_recharge_id'], unique=False)
    op.create_index('ix_rfid_payout_transfers_status_created', 'rfid_payout_transfers', ['status', 'created_at'], unique=False)
    op.create_index('ix_rfid_payout_transfers_trip_status', 'rfid_payout_transfers', ['scheduled_trip_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rfid_payout_transfers_trip_status', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_status_created', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_source_recharge', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_source_razorpay_payment', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_source_funding_allocation', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_ride', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_razorpay_transfer', table_name='rfid_payout_transfers')
    op.drop_index('ix_rfid_payout_transfers_driver_status', table_name='rfid_payout_transfers')
    op.drop_table('rfid_payout_transfers')
    op.drop_index('ix_rfid_ride_funding_allocations_ride', table_name='rfid_ride_funding_allocations')
    op.drop_index('ix_rfid_ride_funding_allocations_recharge', table_name='rfid_ride_funding_allocations')
    op.drop_index('ix_rfid_ride_funding_allocations_razorpay_payment', table_name='rfid_ride_funding_allocations')
    op.drop_index('ix_rfid_ride_funding_allocations_funding_lot', table_name='rfid_ride_funding_allocations')
    op.drop_table('rfid_ride_funding_allocations')
    op.drop_index('ix_rfid_scan_events_vehicle_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_trip_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_scan_type_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_ride_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_device_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_card_created', table_name='rfid_scan_events')
    op.drop_index('ix_rfid_scan_events_accepted_created', table_name='rfid_scan_events')
    op.drop_table('rfid_scan_events')
    op.drop_index('ix_rfid_trip_rides_vehicle_status', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_trip_status', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_transfer_status', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_dropped_at', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_driver_status', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_card_status', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_boarded_at', table_name='rfid_trip_rides')
    op.drop_index('ix_rfid_trip_rides_account_status', table_name='rfid_trip_rides')
    op.drop_table('rfid_trip_rides')
    # ### end Alembic commands ###
