"""add routes

Revision ID: 89336f803407
Revises: 02086646e638
Create Date: 2026-04-02 16:21:28.665620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89336f803407'
down_revision: Union[str, Sequence[str], None] = '02086646e638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_stops', sa.Column('assume_time_diff_minutes', sa.Integer(), nullable=True))
    op.add_column('trip_bookings', sa.Column('pickup_sequence_no_snapshot', sa.Integer(), nullable=False))
    op.add_column('trip_bookings', sa.Column('dropoff_sequence_no_snapshot', sa.Integer(), nullable=False))
    op.add_column('trip_bookings', sa.Column('payment_hold_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_trip_bookings_passenger_trip'), 'trip_bookings', type_='unique')
    op.create_index('uq_trip_bookings_passenger_trip_active', 'trip_bookings', ['passenger_user_id', 'scheduled_trip_id'], unique=True, postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trip_bookings_passenger_trip_active', table_name='trip_bookings', postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    op.create_unique_constraint(op.f('uq_trip_bookings_passenger_trip'), 'trip_bookings', ['passenger_user_id', 'scheduled_trip_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('trip_bookings', 'payment_hold_expires_at')
    op.drop_column('trip_bookings', 'dropoff_sequence_no_snapshot')
    op.drop_column('trip_bookings', 'pickup_sequence_no_snapshot')
    op.drop_column('route_stops', 'assume_time_diff_minutes')
    # ### end Alembic commands ###
