"""adhaar and pan nullable true

Revision ID: 897f89700e04
Revises: 59a29f0e1725
Create Date: 2026-04-01 12:17:13.167227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897f89700e04'
down_revision: Union[str, Sequence[str], None] = '59a29f0e1725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('driving_license_file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'driving_license_file_path')
    # ### end Alembic commands ###
