"""adhaar and pan nullable true

Revision ID: 8a115b8236b2
Revises: 897f89700e04
Create Date: 2026-04-01 13:52:04.578293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a115b8236b2'
down_revision: Union[str, Sequence[str], None] = '897f89700e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('aadhaar_number', sa.String(length=12), nullable=True))
    op.add_column('driver_profiles', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('driver_profiles', sa.Column('driving_license_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'driving_license_number')
    op.drop_column('driver_profiles', 'pan_number')
    op.drop_column('driver_profiles', 'aadhaar_number')
    # ### end Alembic commands ###
