"""table added

Revision ID: 8a99cddac510
Revises: d9f1a5cd3c8d
Create Date: 2026-05-12 15:02:32.391233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a99cddac510'
down_revision: Union[str, Sequence[str], None] = 'd9f1a5cd3c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_payout_transfer_reversals',
    sa.Column('rfid_payout_transfer_id', sa.String(length=36), nullable=False),
    sa.Column('rfid_ride_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'processed', 'failed', name='rfid_payout_transfer_reversal_status', native_enum=False, create_constraint=True), server_default=sa.text("'created'"), nullable=False),
    sa.Column('razorpay_reversal_id', sa.String(length=120), nullable=True),
    sa.Column('provider_response_json', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requested_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rfid_payout_transfer_reversals_amount_positive'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfid_payout_transfer_id'], ['rfid_payout_transfers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfid_ride_id'], ['rfid_trip_rides.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_payout_transfer_reversals_razorpay', 'rfid_payout_transfer_reversals', ['razorpay_reversal_id'], unique=False)
    op.create_index('ix_rfid_payout_transfer_reversals_ride', 'rfid_payout_transfer_reversals', ['rfid_ride_id'], unique=False)
    op.create_index('ix_rfid_payout_transfer_reversals_status_created', 'rfid_payout_transfer_reversals', ['status', 'created_at'], unique=False)
    op.create_index('ix_rfid_payout_transfer_reversals_transfer', 'rfid_payout_transfer_reversals', ['rfid_payout_transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_rfid_payout_transfer_reversals_transfer', table_name='rfid_payout_transfer_reversals')
    op.drop_index('ix_rfid_payout_transfer_reversals_status_created', table_name='rfid_payout_transfer_reversals')
    op.drop_index('ix_rfid_payout_transfer_reversals_ride', table_name='rfid_payout_transfer_reversals')
    op.drop_index('ix_rfid_payout_transfer_reversals_razorpay', table_name='rfid_payout_transfer_reversals')
    op.drop_table('rfid_payout_transfer_reversals')
    # ### end Alembic commands ###
