"""table relation added

Revision ID: 8b8743a25900
Revises: 7f5ebabcb49c
Create Date: 2026-06-01 10:48:39.501816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8743a25900'
down_revision: Union[str, Sequence[str], None] = '7f5ebabcb49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_sessions',
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_stop_id', sa.String(length=36), nullable=False),
    sa.Column('dropoff_stop_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_sequence_no_snapshot', sa.Integer(), nullable=False),
    sa.Column('dropoff_sequence_no_snapshot', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'confirmed', 'cancelled', 'expired', name='booking_session_status', native_enum=False, create_constraint=True), server_default=sa.text("'pending_payment'"), nullable=False),
    sa.Column('total_fare_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dropoff_sequence_no_snapshot > pickup_sequence_no_snapshot', name='ck_booking_sessions_dropoff_after_pickup'),
    sa.CheckConstraint('pickup_sequence_no_snapshot > 0', name='ck_booking_sessions_pickup_sequence_positive'),
    sa.CheckConstraint('pickup_stop_id <> dropoff_stop_id', name='ck_booking_sessions_pickup_dropoff_different'),
    sa.CheckConstraint('total_fare_amount >= 0', name='ck_booking_sessions_total_fare_nonnegative'),
    sa.ForeignKeyConstraint(['dropoff_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_sessions_hold_expiry', 'booking_sessions', ['status', 'payment_hold_expires_at'], unique=False)
    op.create_index('ix_booking_sessions_owner_status', 'booking_sessions', ['owner_user_id', 'status'], unique=False)
    op.create_index('ix_booking_sessions_trip_status', 'booking_sessions', ['scheduled_trip_id', 'status'], unique=False)
    op.create_table('booking_session_payments',
    sa.Column('booking_session_id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'refunded', name='booking_session_payment_status', native_enum=False, create_constraint=True), server_default=sa.text("'created'"), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_booking_session_payments_amount_positive'),
    sa.ForeignKeyConstraint(['booking_session_id'], ['booking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('ix_booking_session_payments_session_status', 'booking_session_payments', ['booking_session_id', 'status'], unique=False)
    op.add_column('trip_bookings', sa.Column('booking_session_id', sa.String(length=36), nullable=True))
    op.add_column('trip_bookings', sa.Column('booked_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('trip_bookings', sa.Column('traveller_profile_id', sa.String(length=36), nullable=True))
    op.add_column('trip_bookings', sa.Column('traveller_name_snapshot', sa.String(length=120), nullable=True))
    op.add_column('trip_bookings', sa.Column('traveller_phone_snapshot', sa.String(length=20), nullable=True))
    op.add_column('trip_bookings', sa.Column('traveller_email_snapshot', sa.String(length=255), nullable=True))
    op.add_column('trip_bookings', sa.Column('traveller_relationship_label_snapshot', sa.String(length=80), nullable=True))
    op.create_index('ix_trip_bookings_booked_by_user', 'trip_bookings', ['booked_by_user_id'], unique=False)
    op.create_index('ix_trip_bookings_booking_session', 'trip_bookings', ['booking_session_id'], unique=False)
    op.create_index('ix_trip_bookings_traveller_profile', 'trip_bookings', ['traveller_profile_id'], unique=False)
    op.create_foreign_key(None, 'trip_bookings', 'passenger_traveller_profiles', ['traveller_profile_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trip_bookings', 'booking_sessions', ['booking_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trip_bookings', 'users', ['booked_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_bookings', type_='foreignkey')
    op.drop_constraint(None, 'trip_bookings', type_='foreignkey')
    op.drop_constraint(None, 'trip_bookings', type_='foreignkey')
    op.drop_index('ix_trip_bookings_traveller_profile', table_name='trip_bookings')
    op.drop_index('ix_trip_bookings_booking_session', table_name='trip_bookings')
    op.drop_index('ix_trip_bookings_booked_by_user', table_name='trip_bookings')
    op.drop_column('trip_bookings', 'traveller_relationship_label_snapshot')
    op.drop_column('trip_bookings', 'traveller_email_snapshot')
    op.drop_column('trip_bookings', 'traveller_phone_snapshot')
    op.drop_column('trip_bookings', 'traveller_name_snapshot')
    op.drop_column('trip_bookings', 'traveller_profile_id')
    op.drop_column('trip_bookings', 'booked_by_user_id')
    op.drop_column('trip_bookings', 'booking_session_id')
    op.drop_index('ix_booking_session_payments_session_status', table_name='booking_session_payments')
    op.drop_table('booking_session_payments')
    op.drop_index('ix_booking_sessions_trip_status', table_name='booking_sessions')
    op.drop_index('ix_booking_sessions_owner_status', table_name='booking_sessions')
    op.drop_index('ix_booking_sessions_hold_expiry', table_name='booking_sessions')
    op.drop_table('booking_sessions')
    # ### end Alembic commands ###
