"""table added new

Revision ID: 929968f9cb4f
Revises: 8a99cddac510
Create Date: 2026-05-13 11:52:48.100049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929968f9cb4f'
down_revision: Union[str, Sequence[str], None] = '8a99cddac510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('platform_settings', sa.Column('allow_driver_rfid_seat_reservation', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'allow_driver_rfid_seat_reservation')

    # ### end Alembic commands ###
