"""add a table and relationship

Revision ID: a2e4d4658952
Revises: db276967c13b
Create Date: 2026-04-03 10:09:53.315245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e4d4658952'
down_revision: Union[str, Sequence[str], None] = 'db276967c13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_trips', sa.Column('started_at_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('scheduled_trips', sa.Column('started_at_long', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('scheduled_trips', sa.Column('ended_at_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('scheduled_trips', sa.Column('ended_at_long', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_trips', 'ended_at_long')
    op.drop_column('scheduled_trips', 'ended_at_lat')
    op.drop_column('scheduled_trips', 'started_at_long')
    op.drop_column('scheduled_trips', 'started_at_lat')
    # ### end Alembic commands ###
