"""Recreate the whole scheama

Revision ID: afd209c85377
Revises: 
Create Date: 2026-04-13 14:18:23.338279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd209c85377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'signup', name='otp_purpose', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_requests_email_expires_at', 'otp_requests', ['email', 'expires_at'], unique=False)
    op.create_table('platform_settings',
    sa.Column('settings_key', sa.String(length=32), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('commission_percent >= 0 AND commission_percent <= 100', name='ck_platform_settings_commission_percent_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settings_key')
    )
    op.create_table('routes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("code <> ''", name='ck_routes_code_nonempty'),
    sa.CheckConstraint("name <> ''", name='ck_routes_name_nonempty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stops',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("name <> ''", name='ck_stops_name_nonempty'),
    sa.CheckConstraint('lat >= -90 AND lat <= 90', name='ck_stops_lat_range'),
    sa.CheckConstraint('lng >= -180 AND lng <= 180', name='ck_stops_lng_range'),
    sa.CheckConstraint('radius_meters > 0', name='ck_stops_radius_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'driver', 'passenger', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("email <> ''", name='ck_users_email_nonempty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('driver_payout_details',
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('account_holder_name', sa.String(length=120), nullable=False),
    sa.Column('bank_account_number', sa.String(length=64), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('razorpay_linked_account_id', sa.String(length=64), nullable=True),
    sa.Column('linked_account_status', sa.Enum('not_created', 'active', 'blocked', 'deleted', name='linked_account_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_payout_eligible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_holder_name <> ''", name='ck_driver_payout_account_holder_name_nonempty'),
    sa.CheckConstraint("bank_account_number <> ''", name='ck_driver_payout_bank_account_nonempty'),
    sa.CheckConstraint("ifsc_code <> ''", name='ck_driver_payout_ifsc_nonempty'),
    sa.CheckConstraint("phone_number <> ''", name='ck_driver_payout_phone_nonempty'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_user_id'),
    sa.UniqueConstraint('razorpay_linked_account_id')
    )
    op.create_table('driver_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('profile_picture_path', sa.String(length=255), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('driving_license_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_file_path', sa.String(length=255), nullable=True),
    sa.Column('pan_file_path', sa.String(length=255), nullable=True),
    sa.Column('driving_license_file_path', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=64), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('passbook_file_path', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('draft', 'pending', 'verified', 'rejected', name='driver_verification_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('lifecycle_status', sa.Enum('active', 'banned', 'deleted', name='driver_lifecycle_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('duration_payable_days', sa.Integer(), nullable=True),
    sa.Column('verification_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("full_name <> ''", name='ck_driver_profiles_full_name_nonempty'),
    sa.CheckConstraint("phone <> ''", name='ck_driver_profiles_phone_nonempty'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('passenger_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('profile_picture_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("full_name <> ''", name='ck_passenger_profiles_full_name_nonempty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('route_fares',
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_stop_id', sa.String(length=36), nullable=False),
    sa.Column('dropoff_stop_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_route_fares_amount_nonnegative'),
    sa.CheckConstraint('pickup_stop_id <> dropoff_stop_id', name='ck_route_fares_pickup_dropoff_different'),
    sa.ForeignKeyConstraint(['dropoff_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'pickup_stop_id', 'dropoff_stop_id', name='uq_route_fares_route_pickup_dropoff')
    )
    op.create_table('route_stops',
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('stop_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('assume_time_diff_minutes', sa.Integer(), nullable=True),
    sa.Column('boarding_allowed', sa.Boolean(), nullable=False),
    sa.Column('deboarding_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence_no > 0', name='ck_route_stops_sequence_positive'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_no', name='uq_route_stops_route_sequence')
    )
    op.create_index('ix_route_stops_route_id_stop_id', 'route_stops', ['route_id', 'stop_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolved', 'rejected', name='support_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resolved_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("description <> ''", name='ck_support_description_nonempty'),
    sa.CheckConstraint("subject <> ''", name='ck_support_subject_nonempty'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_user_status', 'support_tickets', ['user_id', 'status'], unique=False)
    op.create_table('user_notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.CheckConstraint("message <> ''", name='ck_user_notifications_message_nonempty'),
    sa.CheckConstraint("title <> ''", name='ck_user_notifications_title_nonempty'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notifications_user_created', 'user_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_user_notifications_user_read', 'user_notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_user_sessions_user_id_expires_at', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('vehicles',
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('registration_number', sa.String(length=32), nullable=False),
    sa.Column('registration_valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_name', sa.String(length=80), nullable=False),
    sa.Column('vehicle_model', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('rc_file_path', sa.String(length=255), nullable=False),
    sa.Column('rear_photo_file_path', sa.String(length=255), nullable=False),
    sa.Column('verification_status', sa.Enum('draft', 'pending', 'verified', 'rejected', name='vehicle_verification_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('verification_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_reason', sa.Text(), nullable=True),
    sa.Column('inspection_status', sa.Enum('pending', 'approved', 'rejected', name='vehicle_inspection_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("color <> ''", name='ck_vehicles_color_nonempty'),
    sa.CheckConstraint("registration_number <> ''", name='ck_vehicles_registration_number_nonempty'),
    sa.CheckConstraint("vehicle_model <> ''", name='ck_vehicles_vehicle_model_nonempty'),
    sa.CheckConstraint("vehicle_name <> ''", name='ck_vehicles_vehicle_name_nonempty'),
    sa.CheckConstraint('seat_count > 0', name='ck_vehicles_seat_count_positive'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_user_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('scheduled_trips',
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('emergency_stop_request_status', sa.Enum('approved', 'rejected', 'pending', name='emergency_stop_request_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', 'premature_end', 'premature_end_requested', name='scheduled_trip_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('started_at_long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ended_at_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ended_at_long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('started_near_stop_id', sa.String(length=36), nullable=True),
    sa.Column('ended_near_stop_id', sa.String(length=36), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('premature_end_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('planned_end_at > planned_start_at', name='ck_scheduled_trips_planned_window_valid'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ended_near_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['started_near_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_trips_driver_start', 'scheduled_trips', ['driver_user_id', 'planned_start_at'], unique=False)
    op.create_index('ix_scheduled_trips_route_start', 'scheduled_trips', ['route_id', 'planned_start_at'], unique=False)
    op.create_index('ix_scheduled_trips_vehicle_start', 'scheduled_trips', ['vehicle_id', 'planned_start_at'], unique=False)
    op.create_table('trip_bookings',
    sa.Column('passenger_user_id', sa.String(length=36), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_stop_id', sa.String(length=36), nullable=False),
    sa.Column('dropoff_stop_id', sa.String(length=36), nullable=False),
    sa.Column('booking_status', sa.Enum('pending_payment', 'booked', 'boarded', 'completed', 'cancelled', 'missed', name='booking_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pickup_sequence_no_snapshot', sa.Integer(), nullable=False),
    sa.Column('dropoff_sequence_no_snapshot', sa.Integer(), nullable=False),
    sa.Column('payment_hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commission_percent_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transfer_status', sa.Enum('not_ready', 'ready', 'transferred', 'withheld', 'reversed', 'failed', name='transfer_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('transfer_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withheld_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_attempt_count', sa.Integer(), nullable=True),
    sa.Column('boarded_near_stop_id', sa.String(length=36), nullable=True),
    sa.Column('completed_near_stop_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('commission_amount >= 0', name='ck_trip_bookings_commission_amount_nonnegative'),
    sa.CheckConstraint('commission_percent_snapshot >= 0 AND commission_percent_snapshot <= 100', name='ck_trip_bookings_commission_percent_range'),
    sa.CheckConstraint('driver_payout_amount >= 0', name='ck_trip_bookings_driver_payout_nonnegative'),
    sa.CheckConstraint('dropoff_sequence_no_snapshot > pickup_sequence_no_snapshot', name='ck_trip_bookings_dropoff_after_pickup'),
    sa.CheckConstraint('fare_amount >= 0', name='ck_trip_bookings_fare_nonnegative'),
    sa.CheckConstraint('pickup_sequence_no_snapshot > 0', name='ck_trip_bookings_pickup_sequence_positive'),
    sa.CheckConstraint('pickup_stop_id <> dropoff_stop_id', name='ck_trip_bookings_pickup_dropoff_different'),
    sa.ForeignKeyConstraint(['boarded_near_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_near_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dropoff_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_bookings_status_refund_retry_after', 'trip_bookings', ['booking_status', 'refund_retry_after'], unique=False)
    op.create_index('ix_trip_bookings_trip_status', 'trip_bookings', ['scheduled_trip_id', 'booking_status'], unique=False)
    op.create_index('uq_trip_bookings_passenger_trip_active', 'trip_bookings', ['passenger_user_id', 'scheduled_trip_id'], unique=True, postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    op.create_table('trip_events',
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('stop_id', sa.String(length=36), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_trip_id', 'stop_id', name='uq_trip_events_trip_stop')
    )
    op.create_index('ix_trip_events_trip_stop', 'trip_events', ['scheduled_trip_id', 'stop_id'], unique=False)
    op.create_table('booking_payments',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'refunded', name='booking_payment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_booking_payments_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['trip_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('ix_booking_payments_booking_status', 'booking_payments', ['booking_id', 'status'], unique=False)
    op.create_table('booking_ratings',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_user_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('trip_rating', sa.Integer(), nullable=False),
    sa.Column('driver_rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('driver_rating >= 1 AND driver_rating <= 5', name='ck_booking_ratings_driver_range'),
    sa.CheckConstraint('trip_rating >= 1 AND trip_rating <= 5', name='ck_booking_ratings_trip_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['trip_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passenger_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('payout_adjustments',
    sa.Column('origin_booking_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_type', sa.Enum('fine', 'deduction', name='payout_adjustment_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('decision_status', sa.Enum('pending', 'included', 'excluded', name='payout_adjustment_decision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("((decision_status = 'pending' AND decided_by_admin_id IS NULL AND decided_at IS NULL) OR (decision_status IN ('included', 'excluded') AND decided_by_admin_id IS NOT NULL AND decided_at IS NOT NULL))", name='ck_payout_adjustments_decision_consistent'),
    sa.CheckConstraint("reason_text <> ''", name='ck_payout_adjustments_reason_text_nonempty'),
    sa.CheckConstraint('amount > 0', name='ck_payout_adjustments_amount_positive'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_booking_id'], ['trip_bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payout_adjustments_created_by_admin', 'payout_adjustments', ['created_by_admin_id'], unique=False)
    op.create_index('ix_payout_adjustments_decided_by_admin', 'payout_adjustments', ['decided_by_admin_id'], unique=False)
    op.create_index('ix_payout_adjustments_origin_booking_decision', 'payout_adjustments', ['origin_booking_id', 'decision_status'], unique=False)
    op.create_table('trip_scan_events',
    sa.Column('scheduled_trip_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_type', sa.Enum('board', 'drop', name='scan_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scan_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('scan_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('matched_stop_id', sa.String(length=36), nullable=True),
    sa.Column('within_radius', sa.Boolean(), nullable=False),
    sa.Column('qr_payload_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('scan_lat >= -90 AND scan_lat <= 90', name='ck_trip_scan_events_lat_range'),
    sa.CheckConstraint('scan_lng >= -180 AND scan_lng <= 180', name='ck_trip_scan_events_lng_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['trip_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['matched_stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_trip_id'], ['scheduled_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_scan_events_trip_booking', 'trip_scan_events', ['scheduled_trip_id', 'booking_id'], unique=False)
    op.create_table('booking_transfers',
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('source_booking_payment_id', sa.String(length=36), nullable=False),
    sa.Column('linked_account_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_transfer_id', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'processed', 'failed', 'reversed', name='booking_transfer_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_booking_transfers_amount_nonnegative'),
    sa.ForeignKeyConstraint(['booking_id'], ['trip_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_booking_payment_id'], ['booking_payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('razorpay_transfer_id')
    )
    op.create_table('payout_adjustment_applications',
    sa.Column('payout_adjustment_id', sa.String(length=36), nullable=False),
    sa.Column('applied_on_booking_id', sa.String(length=36), nullable=False),
    sa.Column('booking_transfer_id', sa.String(length=36), nullable=True),
    sa.Column('applied_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('applied_amount > 0', name='ck_payout_adjustment_applications_amount_positive'),
    sa.ForeignKeyConstraint(['applied_by_admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['applied_on_booking_id'], ['trip_bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_transfer_id'], ['booking_transfers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_adjustment_id'], ['payout_adjustments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_adjustment_id', 'applied_on_booking_id', name='uq_payout_adjustment_application_once_per_booking')
    )
    op.create_index('ix_payout_adjustment_applications_adjustment', 'payout_adjustment_applications', ['payout_adjustment_id'], unique=False)
    op.create_index('ix_payout_adjustment_applications_applied_booking', 'payout_adjustment_applications', ['applied_on_booking_id'], unique=False)
    op.create_index('ix_payout_adjustment_applications_applied_by_admin', 'payout_adjustment_applications', ['applied_by_admin_id'], unique=False)
    op.create_index('ix_payout_adjustment_applications_transfer', 'payout_adjustment_applications', ['booking_transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payout_adjustment_applications_transfer', table_name='payout_adjustment_applications')
    op.drop_index('ix_payout_adjustment_applications_applied_by_admin', table_name='payout_adjustment_applications')
    op.drop_index('ix_payout_adjustment_applications_applied_booking', table_name='payout_adjustment_applications')
    op.drop_index('ix_payout_adjustment_applications_adjustment', table_name='payout_adjustment_applications')
    op.drop_table('payout_adjustment_applications')
    op.drop_table('booking_transfers')
    op.drop_index('ix_trip_scan_events_trip_booking', table_name='trip_scan_events')
    op.drop_table('trip_scan_events')
    op.drop_index('ix_payout_adjustments_origin_booking_decision', table_name='payout_adjustments')
    op.drop_index('ix_payout_adjustments_decided_by_admin', table_name='payout_adjustments')
    op.drop_index('ix_payout_adjustments_created_by_admin', table_name='payout_adjustments')
    op.drop_table('payout_adjustments')
    op.drop_table('booking_ratings')
    op.drop_index('ix_booking_payments_booking_status', table_name='booking_payments')
    op.drop_table('booking_payments')
    op.drop_index('ix_trip_events_trip_stop', table_name='trip_events')
    op.drop_table('trip_events')
    op.drop_index('uq_trip_bookings_passenger_trip_active', table_name='trip_bookings', postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    op.drop_index('ix_trip_bookings_trip_status', table_name='trip_bookings')
    op.drop_index('ix_trip_bookings_status_refund_retry_after', table_name='trip_bookings')
    op.drop_table('trip_bookings')
    op.drop_index('ix_scheduled_trips_vehicle_start', table_name='scheduled_trips')
    op.drop_index('ix_scheduled_trips_route_start', table_name='scheduled_trips')
    op.drop_index('ix_scheduled_trips_driver_start', table_name='scheduled_trips')
    op.drop_table('scheduled_trips')
    op.drop_table('vehicles')
    op.drop_index('ix_user_sessions_user_id_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_notifications_user_read', table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_created', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('ix_support_user_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_route_stops_route_id_stop_id', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_table('route_fares')
    op.drop_table('passenger_profiles')
    op.drop_table('driver_profiles')
    op.drop_table('driver_payout_details')
    op.drop_table('users')
    op.drop_table('stops')
    op.drop_table('routes')
    op.drop_table('platform_settings')
    op.drop_index('ix_otp_requests_email_expires_at', table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
