"""Booking Payment table is added the GST part

Revision ID: beaf062bcd7b
Revises: ebb8b9a272c1
Create Date: 2026-07-09 15:18:44.769433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaf062bcd7b'
down_revision: Union[str, Sequence[str], None] = 'ebb8b9a272c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_payments', sa.Column('base_fare_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('booking_payments', sa.Column('cgst_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('booking_payments', sa.Column('sgst_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('booking_payments', sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('booking_payments', sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_payments', 'sgst_amount')
    op.drop_column('booking_payments', 'cgst_amount')
    op.drop_column('booking_payments', 'sgst_percent')
    op.drop_column('booking_payments', 'cgst_percent')
    op.drop_column('booking_payments', 'base_fare_amount')
    # ### end Alembic commands ###
