"""adhaar and pan nullable true

Revision ID: c75633fcf12c
Revises: 8a115b8236b2
Create Date: 2026-04-01 14:35:01.778635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75633fcf12c'
down_revision: Union[str, Sequence[str], None] = '8a115b8236b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('bank_account_number', sa.String(length=64), nullable=True))
    op.add_column('driver_profiles', sa.Column('ifsc_code', sa.String(length=20), nullable=True))
    op.add_column('driver_profiles', sa.Column('passbook_file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_profiles', 'passbook_file_path')
    op.drop_column('driver_profiles', 'ifsc_code')
    op.drop_column('driver_profiles', 'bank_account_number')
    # ### end Alembic commands ###
