"""trip_bookings have been modified add the GST part there

Revision ID: c9183ec53a03
Revises: beaf062bcd7b
Create Date: 2026-07-10 14:59:44.460619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9183ec53a03'
down_revision: Union[str, Sequence[str], None] = 'beaf062bcd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_bookings', sa.Column('taxable_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trip_bookings', sa.Column('cgst_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('trip_bookings', sa.Column('sgst_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('trip_bookings', sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trip_bookings', sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_bookings', 'sgst_amount')
    op.drop_column('trip_bookings', 'cgst_amount')
    op.drop_column('trip_bookings', 'sgst_percent')
    op.drop_column('trip_bookings', 'cgst_percent')
    op.drop_column('trip_bookings', 'taxable_amount')
    # ### end Alembic commands ###
