"""db change for signup login new chnange and otp change in db check the migration all done or not

Revision ID: cf1efc547462
Revises: 6fb141b21526
Create Date: 2026-05-19 16:40:37.095142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1efc547462'
down_revision: Union[str, Sequence[str], None] = '6fb141b21526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
