"""add the col in vehicle

Revision ID: d51d69524c5c
Revises: 6925d0521c43
Create Date: 2026-04-09 12:22:53.118968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51d69524c5c'
down_revision: Union[str, Sequence[str], None] = '6925d0521c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('vehicles', sa.Column('registration_valid_till', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'registration_valid_till')
    op.alter_column('scheduled_trips', 'status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', 'premature_end', name='scheduled_trip_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
