"""col and contrains are added

Revision ID: d9f1a5cd3c8d
Revises: 3912fc1fde39
Create Date: 2026-05-12 12:31:04.277720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f1a5cd3c8d'
down_revision: Union[str, Sequence[str], None] = '3912fc1fde39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('rfid_payout_transfers', sa.Column('reversed_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfid_payout_transfers', 'reversed_amount')

    # ### end Alembic commands ###
