"""nullable false true

Revision ID: e11ea3bede0e
Revises: 152d8fb288d5
Create Date: 2026-05-19 14:17:39.056135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11ea3bede0e'
down_revision: Union[str, Sequence[str], None] = '152d8fb288d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid_trip_rides', 'board_lat',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    op.alter_column('rfid_trip_rides', 'board_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfid_trip_rides', 'board_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    op.alter_column('rfid_trip_rides', 'board_lat',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    # ### end Alembic commands ###
