"""small change

Revision ID: e35a950e0a9a
Revises: e2f23e0966f0
Create Date: 2026-06-02 14:00:39.614694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35a950e0a9a'
down_revision: Union[str, Sequence[str], None] = 'e2f23e0966f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_trip_bookings_passenger_trip_active'), table_name='trip_bookings', postgresql_where="((booking_status)::text = ANY ((ARRAY['pending_payment'::character varying, 'booked'::character varying, 'boarded'::character varying])::text[]))")
    op.create_index('ix_trip_bookings_passenger_trip_active', 'trip_bookings', ['passenger_user_id', 'scheduled_trip_id'], unique=False, postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_bookings_passenger_trip_active', table_name='trip_bookings', postgresql_where=sa.text("booking_status IN ('pending_payment', 'booked', 'boarded')"))
    op.create_index(op.f('uq_trip_bookings_passenger_trip_active'), 'trip_bookings', ['passenger_user_id', 'scheduled_trip_id'], unique=True, postgresql_where="((booking_status)::text = ANY ((ARRAY['pending_payment'::character varying, 'booked'::character varying, 'boarded'::character varying])::text[]))")
    # ### end Alembic commands ###
