"""create multiple coloumns

Revision ID: eb21a1eba0c4
Revises: 28790fa0164a
Create Date: 2026-04-17 14:35:10.596579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb21a1eba0c4'
down_revision: Union[str, Sequence[str], None] = '28790fa0164a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('front_photo_file_path', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('interior_photo_file_path', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('left_side_file_path', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('right_side_file_path', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('insurance_document', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('pollution_document', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('owner_aadhaar_card', sa.String(length=255), nullable=True))
    op.add_column('vehicles', sa.Column('owner_name', sa.String(length=120), nullable=True))
    op.drop_column('vehicles', 'chassis_no')
    op.drop_column('vehicles', 'rc_owner_name')
    op.drop_column('vehicles', 'engine_number')
    op.drop_column('vehicles', 'rc_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('rc_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('engine_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('rc_owner_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('vehicles', sa.Column('chassis_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'owner_name')
    op.drop_column('vehicles', 'owner_aadhaar_card')
    op.drop_column('vehicles', 'pollution_document')
    op.drop_column('vehicles', 'insurance_document')
    op.drop_column('vehicles', 'right_side_file_path')
    op.drop_column('vehicles', 'left_side_file_path')
    op.drop_column('vehicles', 'interior_photo_file_path')
    op.drop_column('vehicles', 'front_photo_file_path')
    # ### end Alembic commands ###
