"""schema update

Revision ID: f515c2ae4a88
Revises: eb21a1eba0c4
Create Date: 2026-04-17 14:39:36.120558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f515c2ae4a88'
down_revision: Union[str, Sequence[str], None] = 'eb21a1eba0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('commercial_policy_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'commercial_policy_json')
    # ### end Alembic commands ###
