"""schema the trips

Revision ID: f74919ccece2
Revises: f515c2ae4a88
Create Date: 2026-04-17 16:42:51.222010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74919ccece2'
down_revision: Union[str, Sequence[str], None] = 'f515c2ae4a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_trips', sa.Column('last_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('scheduled_trips', sa.Column('last_lng', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_trips', 'last_lng')
    op.drop_column('scheduled_trips', 'last_lat')
    # ### end Alembic commands ###
